//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIYU_SecureID.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIYU_SecureID.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;01&quot;: {
        ///    &quot;region_name&quot;: &quot;REGION I&quot;,
        ///    &quot;province_list&quot;: {
        ///      &quot;ILOCOS NORTE&quot;: {
        ///        &quot;municipality_list&quot;: {
        ///          &quot;ADAMS&quot;: {
        ///            &quot;barangay_list&quot;: [
        ///              &quot;ADAMS (POB.)&quot;
        ///            ]
        ///          },
        ///          &quot;BACARRA&quot;: {
        ///            &quot;barangay_list&quot;: [
        ///              &quot;BANI&quot;,
        ///              &quot;BUYON&quot;,
        ///              &quot;CABARUAN&quot;,
        ///              &quot;CABULALAAN&quot;,
        ///              &quot;CABUSLIGAN&quot;,
        ///              &quot;CADARATAN&quot;,
        ///              &quot;CALIOET-LIBONG&quot;,
        ///              &quot;CASILIAN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string auto_complete_address {
            get {
                return ResourceManager.GetString("auto_complete_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_secureID {
            get {
                object obj = ResourceManager.GetObject("icon_secureID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_close {
            get {
                object obj = ResourceManager.GetObject("icons_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_minimize {
            get {
                object obj = ResourceManager.GetObject("icons_minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_restore_down {
            get {
                object obj = ResourceManager.GetObject("icons_restore_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_square {
            get {
                object obj = ResourceManager.GetObject("icons_square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4902846422877~SIA~GEORGE JOSEPH~MANILA~~MALE~B+~8 NOVEMBER 2003~QUEZON~CITY1~BARANGAY1~MARRIED~iVBORw0KGgoAAAANSUhEUgAAAtAAAALQCAIAAAA2NdDLAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAP+lSURBVHhevP3ncxtZmu/71ssbcW+cMzPdXU6enjAECICgAQl6KxqJpEiJRjSi994TJEiA3nvZklSue0/39OzZO859cf+5+1v5ZD5YyAQgVnXPzvgGI5FIQCoD4MOVKxNf1WaloMqcJFThEZXnpVR4U1FZbpJcSU5CgftRtsvldqSn29LSLCZLakpqchIypSRjHVuy3AUos9CLsory3QV5jkx3mjM9MTHx0aNHd+7c+fbbb7/++us//elPf9SWP2jLvyoLVtQ7/vhH7PmNsty9excPT0pKSk1NNZvNFmWxp1ndL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ID_info {
            get {
                return ResourceManager.GetString("ID_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ID_QR {
            get {
                return ResourceManager.GetString("ID_QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap secureid_back {
            get {
                object obj = ResourceManager.GetObject("secureid_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap secureid_front {
            get {
                object obj = ResourceManager.GetObject("secureid_front", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
